MutationDecorator:
    type: object
    decorator: true
    config:
        fields:
            CreateOrder:
                type: Order!
                description: "Creates complete order with products and addresses"
                args:
                    input:
                        type: OrderInput!
                        validation: cascade
                resolve: "@=mutation('create_order', [args, validator])"
            Login:
                type: Token!
                description: "Login user and return access and refresh tokens"
                args:
                    input:
                        type: LoginInput!
                resolve: "@=mutation('user_login', [args])"
            Logout:
                type: Boolean!
                description: "Logout user"
                resolve: "@=mutation('user_logout')"
            RefreshTokens:
                type: Token!
                description: "Refreshes access and refresh tokens"
                args:
                    input:
                        type: RefreshTokenInput!
                resolve: "@=mutation('refresh_tokens', [args])"
            ChangePassword:
                type: 'CurrentCustomerUser!'
                description: "Changes customer user password"
                args:
                    input:
                        type: ChangePasswordInput!
                resolve: "@=mutation('customer_user_change_password', [args])"
            ChangePersonalData:
                type: 'CurrentCustomerUser!'
                description: "Changes customer user personal data"
                args:
                    input:
                        type: ChangePersonalDataInput!
                resolve: "@=mutation('customer_user_change_personal_data', [args])"
